# This is a basic workflow to help you get started with Actions

name: Pipeline CD

# Controls when the workflow will run
on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

  workflow_dispatch:

jobs:
  setup_environ:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_environment.outputs.environment }}
    
    steps:
      - uses: actions/checkout@v4

      - id: "set_environment"
        run: |
          if [[ ${{ github.ref_name }} == dev ]]; then echo "environment=development" >> $GITHUB_OUTPUT; fi
          if [[ ${{ github.ref_name }} == main ]]; then echo "environment=production" >> $GITHUB_OUTPUT; fi

  deploy:
    name: Pipeline Deploy
    runs-on: ubuntu-latest
    needs: [setup_environ]

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          credentials_json: ${{ secrets.CREDENTIALS }}

      - uses: 'google-github-actions/deploy-cloud-functions@v3'
        timeout-minutes: 10
        with:
          name: '${{needs.setup_environ.outputs.environment}}_training_pipeline'
          runtime: 'python39'
          min_instance_count: 0
          max_instance_count: 1
          service_timeout: "120s"
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          memory: "1G"
          source_dir: "./"
          entry_point: "training_pipeline.py"
          event_trigger_type: "google.cloud.pubsub.topic.v1.messagePublished"
          event_trigger_pubsub_topic: "projects/personal-448814/topics/training_pipe_topico"
          event_trigger_retry: "true"



    
    
